# Generated by Django 3.2 on 2021-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_auto_20210425_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='flavour',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
