# Generated by Django 3.2 on 2021-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_auto_20210425_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cakeid',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='eggless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavour',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
