# Generated by Django 3.2 on 2021-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_auto_20210427_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavour',
            field=models.CharField(default='No flavour', max_length=40),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(default='Cake', max_length=40),
        ),
    ]
