# Generated by Django 3.2 on 2021-04-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_auto_20210427_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='cakeid',
        ),
    ]
