# Generated by Django 3.2 on 2021-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_remove_cake_cakeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
