# Generated by Django 3.2 on 2021-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_alter_cake_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='eggless',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='flavour',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='weight',
        ),
        migrations.AlterField(
            model_name='cake',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
