# Generated by Django 3.2 on 2021-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_auto_20210427_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cake',
            name='eggless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cake',
            name='flavour',
            field=models.CharField(default='No flavour', max_length=40),
        ),
        migrations.AddField(
            model_name='cake',
            name='name',
            field=models.CharField(default='Cake', max_length=40),
        ),
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
