# Generated by Django 3.2 on 2021-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_auto_20210427_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
