# Generated by Django 3.2 on 2021-04-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0011_alter_cake_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='flavour',
            field=models.CharField(default='', max_length=40),
        ),
    ]
