# Generated by Django 3.2 on 2021-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0012_alter_cake_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='eggless',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='weight',
        ),
        migrations.AddField(
            model_name='cake',
            name='cakeid',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavour',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
