# Generated by Django 3.2 on 2021-04-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0013_auto_20210427_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='cakeid',
        ),
    ]
