# Generated by Django 3.2 on 2021-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0014_remove_cake_cakeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
