# Generated by Django 3.2 on 2021-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0016_alter_cake_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cake',
            name='eggless',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavour',
            field=models.CharField(max_length=40),
        ),
    ]
