# Generated by Django 3.2 on 2021-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0017_auto_20210427_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
