# Generated by Django 3.2 on 2021-04-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0018_auto_20210427_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
