# Generated by Django 3.2 on 2021-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0019_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.CharField(default='', max_length=400),
        ),
    ]
